---
- hosts: vps
  user: superman
  become: true
  become_user: root
  # Do gather fact, but not here after the pre_tasks that install python on host.
  gather_facts: no
  roles:
    - dev-sec.ssh-hardening

  vars:
    network_ipv6_enable: true
    ssh_listen_to: ['0.0.0.0','::']
    docker_opts: '--ipv6 --fixed-cidr-v6="fe80:1:1::/64"'
    users:
      - "rik"


    # see https://docs.ansible.com/ansible/faq.html#how-do-i-generate-crypted-passwords-for-the-user-module
    # created with:
    # python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.using(rounds=5000).hash(getpass.getpass())"
    # input: you would love to know that right?
    # LATER make this on a per user basis
    password: '$6$ICSMfftYR4MpMsFR$i3ZGDDBp6w4Rh/Re2W9ECCNC6No2C2JDGCkGVwjcMV9geaNXjgIX5.22BAXdZE/x6QsIf3/6fEBKG8kfKrxYD/'

  # Host should contain python2+ for running ansible stuff
  pre_tasks:
    - name: Ensure python is there
      raw: test -e /usr/bin/python || ( apt install -y python-minimal)
    - name: Ensure APT cache is actual
      apt: update_cache=yes
      # Now it is time to gather facts
    - setup:
    - name: Ensure nginx is installed
      apt: name=nginx state=latest
    - name: Esure latest updates are installed
      apt: upgrade=dist
    - name: Check if a reboot is required
      register: file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Reboot the server
      command: /sbin/reboot
      when: file.stat.exists == true

  tasks:
    - include: tasks/ssh.yml
    - include: tasks/ufw.yml
    - include: tasks/nginx.yml
    #- include: tasks/mail.yml
