---
# install docker

- name: Ensure old version of docker is not there
  package:
    name: docker
    state: absent

- name: Ensure old version of docker-engine is not there
  package:
    name: docker-engine
    state: absent

- name: Add docker to repository login_result
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Ensure docker is installed
  package:
    name: docker-ce
    state: present
