---
# install nginx with letsencrypt
# inspired from:
#   https://blog.evantahler.com/ansible-letsencrypt-nginx-and-actionhero-7be135fc6319
#   https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

  - name: Ensure nginx is installed
    apt: name=nginx state=latest

  - apt_repository:
      repo: 'ppa:certbot/certbot'

  - name: Install certbot
    apt: name=python-certbot-nginx state=latest

  - name: Install system nginx config
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: Remove default nginx config
    file: name=/etc/nginx/sites-enabled/default state=absent

  # And now some firewall rules
  - ufw:
     rule: allow
     name: Nginx Full

  # Generate certificates if do not exits
  - name: Check if we've generated a cert already
    stat:
      path: /etc/letsencrypt/live/www.{{ domain_name }}/fullchain.pem
    register: cert_stats

  - name: Ensure /var/www/letsencypt/.well-known/acme-challenge exists
    file:
      path: /var/www/letsencrypt/.well-known/acme-challenge
      state: directory

  - name: Install letsencrypt ACME challenge config for {{ domain_name }}
    template:
      src: templates/letsencrypt-acme-challenge.conf
      dest: /etc/nginx/snippets/letsencrypt-acme-challenge.conf

  # Create a temp site for initial acme challenge
  - name: Install nginx site for initial letsencrypt certificates
    template:
      src: templates/nginx-initial.j2
      dest: /etc/nginx/sites-enabled/initial
    when:
        - cert_stats.stat.exists == false

  - name: Ensure /var/www/initial exists
    file:
      path: /var/www/initial
      state: directory
    when:
      - cert_stats.stat.exists == false

  - name: Restart nginx to activate initial letsencrypt site
    service: name=nginx state=restarted
    when:
        - cert_stats.stat.exists == false

  - name: Generate certs (first time)
    shell:  "certbot certonly --webroot --webroot-path /var/www/letsencrypt -d www.{{ domain_name }} -d {{ domain_name }} -d mail.{{ domain_name }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"
    when:
      - "{{ production }}"
      - cert_stats.stat.exists == false

  - name: Remove initial letsencrypt site config
    file: name=/etc/nginx/sites-enabled/initial state=absent

  - name: Remove nginx site for {{ domain_name }}
    file: name=/etc/nginx/sites-enabled/{{ domain_name }} state=absent

  - name: Install nginx site for {{ domain_name }}
    template:
      src: templates/nginx-site.j2
      dest: /etc/nginx/sites-enabled/{{ domain_name }}

  - name: Ensure /var/www/{{ domain_name }} exists
    file:
      path: /var/www/{{ domain_name }}
      state: directory

  - name: Install default index.html page
    template:
      src: templates/index.html.j2
      dest: /var/www/{{ domain_name }}/index.html

  - name: Verify is dhparam.pem exists
    stat:
      path: /etc/nginx/dhparams.pem
    register: p

  - name: Generate dhparams
    shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
    args:
      creates: /etc/nginx/dhparams.pem
    when: p.stat.exists == false

  - name: Restart nginx to activate site {{ domain_name }}
    service: name=nginx state=restarted
    when:
      - "{{ production }}"

  - name: Ensure crontab for auto renewal is there
    cron:
      name: "renew certifcates nginx/letsencrypt"
      minute: "13"
      hour: "13"
      job: "/usr/bin/certbot renew --quiet --renew-hook 'openssl dhparam -out /etc/nginx/dhparams.pem 2048 && service nginx reload'"
    when:
        - "{{ production }}"
