---

- name: Ensure Universal firewall is enabled
  ufw:
    state: enabled
    policy: reject
    logging: off

- name: Ensure SSH is allowed
  ufw:
    rule: allow
    name: OpenSSH

- name: Ensure Nginx is allowed
  ufw:
   rule: allow
   name: Nginx Full
